event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /eventos

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /bo

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /

image:
    resource: "@ImageBundle/Resources/config/routing.yml"
    prefix:   /