blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /