# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Movidon\BackendBundle\Entity\AdminUser: { algorithm: sha512, iterations: 10 }
        #Movidon\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #user:
        #    entity: { class: Movidon\UserBundle\Entity\User, property: email }
        admin_user:
            entity: { class: Movidon\BackendBundle\Entity\AdminUser, property: username }
        in_memory:
            memory:
                users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN', 'ROLE_ALLOWED_TO_SWITCH' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        admin:
            pattern: ^/bo
            provider: admin_user
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: /bo
                always_use_default_target_path: true
            logout:
                path: /bo/logout
        #user:
        #    pattern: ^/
        #    provider: user
        #    anonymous: ~
        #    form_login:
        #       login_path: login
        #       check_path: login_check
        #       success_handler: movidon.security.authentication.success_handler
        #       default_target_path: /u/mi-cuenta
        #    logout:
        #       path: logout
        #    remember_me:
        #       key: %secret%
        #       lifetime: 5184000

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/bo/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }