admin_login:
    pattern: /login
    defaults: { _controller: BackendBundle:Backend:login }

admin_login_check:
    pattern: /login_check

admin_logout:
    pattern: /logout

admin_register:
    pattern: /register
    defaults: { _controller: BackendBundle:Backend:register }

admin:
    pattern: /
    defaults: #{ _controller: BackendBundle:Backend:example }
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_index
        permanent: true # this is for 301

admin_index:
    pattern: /dashboard
    defaults: { _controller: BackendBundle:Backend:index }

admin_events:
    resource: "@BackendBundle/Resources/config/routing/event.yml"
    prefix: /e/